# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-14 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturePost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
